name: Go Setup
description: Install Go
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@v6.0.0
      id: setup-go
      with:
        go-version-file: "go.mod"
        cache-dependency-path: go.sum
    - name: Download modules
      shell: bash
      run: go mod download
