name: Go Setup
description: Install Go
runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      id: setup-go
      with:
        go-version-file: "go.mod"
        cache-dependency-path: go.sum
    - name: Download modules
      shell: bash
      run: go mod download
