name: release

permissions: {}

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    timeout-minutes: 10
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: "false"
      - name: Setup go
        uses: ./.github/actions/setup-go
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Bench
        run: make bench
      - name: Set env
        run: |
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(git describe --tags --abbrev=0 --exact-match)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e24998b8b67b290c2fa8b7c14fcfa7de2c5c9b8c # v7.1.0
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_PACKAGE: "github.com/berquerant/k8s-object-diff-go/version"
