name: release

permissions: {}

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    timeout-minutes: 10
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: "false"
      - name: Setup go
        uses: ./.github/actions/setup-go
        with:
          cache: false
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: Bench
        run: make bench
      - name: Set env
        run: |
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(git describe --tags --abbrev=0 --exact-match)" >> $GITHUB_ENV
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_PACKAGE: "github.com/berquerant/k8s-object-diff-go/version"
